import React, { useState, useEffect } from 'react';
import axios from 'axios';

const ManageTimberSales = () => {
  const [sales, setSales] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const fetchSales = async () => {
    setLoading(true);
    setError(null);
    try {
      const token = localStorage.getItem('auth_token');
      const res = await axios.get('/officer/timber-sales', {
        headers: { Authorization: `Bearer ${token}` }
      });
      setSales(res.data);
    } catch (err) {
      console.error("Failed to load timber sales", err.response || err);
      setError(
        `Failed to load timber sales (status ${err.response?.status || 'unknown'}): ` +
        (err.response?.data?.message || err.message)
      );
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchSales();
  }, []);

  const handleDelete = async (id) => {
    if (window.confirm('Are you sure you want to delete this timber sale record?')) {
      try {
        const token = localStorage.getItem('auth_token');
        await axios.delete(`/officer/timber-sales/${id}`, {
          headers: { Authorization: `Bearer ${token}` }
        });
        fetchSales();
      } catch (err) {
        alert("Failed to delete record: " + (err.response?.data?.message || err.message));
      }
    }
  };

  const handleGenerateReport = async (id) => {
    try {
      const token = localStorage.getItem('auth_token');
      const res = await axios.get(`/officer/timber-sales/${id}/report`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      openPrintableReport(res.data.sale);
    } catch (err) {
      console.error('Full error response:', err.response);
      alert("Failed to generate report: " + (err.response?.data?.message || err.message));
    }
  };

  const openPrintableReport = (sale) => {
    const reportWindow = window.open('', '_blank', 'width=700,height=850');
    const rows = [
      ['Sale ID', `#${sale.sale_id}`],
      ['Company', sale.company?.company_name || 'N/A'],
      ['Registration Number', sale.company?.registration_number || '—'],
      ['Cutting Request', sale.request_id ? `#${sale.request_id}` : '—'],
      ['Buyer Name', sale.buyer_name || '—'],
      ['Buyer Contact', sale.buyer_contact || '—'],
      ['Species', sale.species_name || '—'],
      ['Quantity Sold (m³)', sale.quantity_cubic_m ?? '—'],
      ['Unit Price', sale.unit_price ? `Rs. ${Number(sale.unit_price).toFixed(2)}` : '—'],
      ['Total Amount', sale.total_amount ? `Rs. ${Number(sale.total_amount).toFixed(2)}` : '—'],
      ['Sale Date', sale.sale_date || '—'],
      ['Invoice Number', sale.invoice_number || '—'],
    ];

    const rowsHtml = rows.map(([label, value]) => `
      <tr>
        <td style="padding:8px 12px;font-weight:600;color:#333;border-bottom:1px solid #eee;width:220px;">${label}</td>
        <td style="padding:8px 12px;color:#111;border-bottom:1px solid #eee;">${value}</td>
      </tr>
    `).join('');

    reportWindow.document.write(`
      <html>
        <head>
          <title>Officer Report - Sale #${sale.sale_id}</title>
          <style>
            body { font-family: Arial, sans-serif; margin: 0; padding: 32px; color: #222; }
            .header { text-align: center; margin-bottom: 24px; border-bottom: 2px solid #3B6D11; padding-bottom: 16px; }
            .header h1 { margin: 0; font-size: 22px; color: #1a3d0f; }
            .header h1 span { color: #3B6D11; }
            .header p { margin: 4px 0 0; color: #666; font-size: 13px; letter-spacing: 1px; }
            .title { font-size: 18px; font-weight: bold; margin-bottom: 16px; }
            table { width: 100%; border-collapse: collapse; }
            .footer { margin-top: 32px; text-align: center; font-size: 12px; color: #888; border-top: 1px solid #eee; padding-top: 12px; }
            .verified { margin-top: 24px; padding: 12px 16px; background: #f0f7ea; border-left: 4px solid #3B6D11; font-size: 13px; }
            @media print { body { padding: 12px; } }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>Forest<span>Guard</span></h1>
            <p>OFFICER VERIFICATION REPORT — TIMBER SALE</p>
          </div>
          <div class="title">Sale Record Report</div>
          <table>${rowsHtml}</table>
          <div class="verified">
            This report was generated by an authorized Forest Officer for oversight and compliance
            verification purposes under the Forest Guard system.
          </div>
          <div class="footer">
            Generated on ${new Date().toLocaleString()} &mdash; Forest Guard, Ministry of Environment, Sri Lanka
          </div>
        </body>
      </html>
    `);
    reportWindow.document.close();
    reportWindow.focus();
    reportWindow.print();
  };

  return (
    <div>
      <div className="d-flex justify-content-between align-items-center mb-4">
        <h4>Timber Sales Records</h4>
      </div>

      {error && (
        <div className="alert alert-danger" role="alert">
          {error}
        </div>
      )}

      {loading ? (
        <p>Loading sales records...</p>
      ) : (
        <div className="table-responsive bg-white rounded shadow-sm border">
          <table className="table table-hover mb-0">
            <thead className="table-light">
              <tr>
                <th>ID</th>
                <th>Company</th>
                <th>Cutting Request</th>
                <th>Quantity Sold (m³)</th>
                <th>Buyer Name</th>
                <th>Sale Date</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {sales.length > 0 ? sales.map(sale => (
                <tr key={sale.sale_id}>
                  <td>#{sale.sale_id}</td>
                  <td>{sale.company?.company_name || 'N/A'}</td>
                  <td>{sale.request_id ? `#${sale.request_id}` : '—'}</td>
                  <td>{sale.quantity_cubic_m ?? '—'}</td>
                  <td>{sale.buyer_name}</td>
                  <td>{sale.sale_date}</td>
                  <td>
                    <button className="btn btn-sm btn-outline-info me-2" onClick={() => handleGenerateReport(sale.sale_id)}>
                      <i className="bi bi-printer me-1"></i>Report
                    </button>
                    <button className="btn btn-sm btn-outline-danger" onClick={() => handleDelete(sale.sale_id)}><i className="bi bi-trash"></i></button>
                  </td>
                </tr>
              )) : (
                <tr>
                  <td colSpan="7" className="text-center py-4 text-muted">No timber sales found</td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
};

export default ManageTimberSales;